# Generated by Django 2.0.2 on 2018-02-22 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'verbose_name': 'process', 'verbose_name_plural': 'processes'},
        ),
    ]
