language: python
python:
    - "3.5.2"
install:
    - pip install -q -r requirements.txt
services:
  - redis-server
script:
    - celery --app=tikal worker --beat --loglevel=info &
    - python manage.py test