# Generated by Django 2.0.2 on 2018-02-22 17:45

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180222_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='process_number',
            field=models.CharField(max_length=20, validators=[core.validators.validate_process_number], verbose_name='número do processo'),
        ),
    ]
